export const chatScreenTheme = {
  assistantMessageAccentColor: "#7ee787",
  borderColor: "#294055",
  borderStyle: "round",
  canvasBackgroundColor: "#08111d",
  errorColor: "#ff7b72",
  mutedTextColor: "#8aa0b5",
  outerPadding: 1,
  panelBackgroundColor: "#0f1726",
  panelGap: 1,
  primaryTextColor: "#e6edf3",
  promptDockBackgroundColor: "#152235",
  selectionAccentColor: "#58d6ff",
  titleAccentColor: "#58d6ff",
  userMessageAccentColor: "#7cc7ff",
  warningColor: "#f6c177",
} as const;
