import { RGBA, SyntaxStyle } from "@opentui/core";
import type { SyntaxHighlightSpanStyle } from "@buli/contracts";
import { chatScreenTheme } from "@buli/assistant-design-tokens";

export const githubLikeTerminalCodeColors = {
  canvas: "#000000",
  foreground: "#F0F6FC",
  muted: "#8B949E",
  subtle: "#6E7681",
  keyword: "#FF7B72",
  string: "#F2CC60",
  number: "#FFA657",
  constant: "#D2A8FF",
  function: "#D2A8FF",
  type: "#FFA657",
  property: "#56D4DD",
  module: "#7EE787",
  punctuation: "#C9D1D9",
  operator: "#FF7B72",
  decorator: "#FFAB70",
  tag: "#FFA657",
  attribute: "#56D4DD",
  comment: "#8B949E",
  diffAddition: "#3FB950",
  diffRemoval: "#FF4D5B",
  diffMetadata: "#79C0FF",
  diffAdditionBackground: "#003D1F",
  diffRemovalBackground: "#4C0610",
  diffAdditionContentBackground: "#00552A",
  diffRemovalContentBackground: "#6E0B18",
} as const;

const codeBlockSyntaxStyleStyles = {
  default: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.foreground) },
  keyword: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.conditional": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.conditional.ternary": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.coroutine": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.directive": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.exception": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.function": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.import": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.modifier": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.operator": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.operator), bold: true },
  "keyword.repeat": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.return": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  "keyword.type": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  string: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.string) },
  "string.escape": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword) },
  "string.regexp": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.string) },
  "string.special.key": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.property) },
  "string.special": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.string) },
  "string.special.url": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.property), underline: true },
  comment: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.comment), italic: true },
  "comment.documentation": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.comment), italic: true },
  number: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.number) },
  "number.float": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.number) },
  boolean: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.constant) },
  constant: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.constant) },
  "constant.builtin": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.constant) },
  constructor: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.type) },
  function: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.function) },
  "function.builtin": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.function) },
  "function.call": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.function) },
  "function.method": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.function) },
  "function.method.call": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.function) },
  type: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.type) },
  "type.builtin": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.type) },
  property: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.property) },
  variable: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.foreground) },
  "variable.builtin": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.constant) },
  "variable.member": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.property) },
  "variable.parameter": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.foreground) },
  parameter: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.foreground) },
  operator: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.operator) },
  punctuation: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.punctuation) },
  "punctuation.bracket": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.punctuation) },
  "punctuation.delimiter": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.punctuation) },
  "punctuation.special": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword) },
  tag: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.tag) },
  attribute: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.attribute) },
  decorator: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.decorator) },
  namespace: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.module) },
  module: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.module) },
  "module.builtin": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.module) },
  import: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword), bold: true },
  escape: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword) },
  character: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.string) },
  "character.special": { fg: RGBA.fromHex(githubLikeTerminalCodeColors.keyword) },
  label: { fg: RGBA.fromHex(githubLikeTerminalCodeColors.property) },
} as const;

export const codeBlockSyntaxStyle = SyntaxStyle.fromStyles(codeBlockSyntaxStyleStyles);

export const assistantMarkdownSyntaxStyle = SyntaxStyle.fromStyles({
  default: { fg: RGBA.fromHex(chatScreenTheme.textPrimary) },
  conceal: { fg: RGBA.fromHex(chatScreenTheme.borderSubtle) },
  "markup.heading": { fg: RGBA.fromHex(chatScreenTheme.textPrimary), bold: true },
  "markup.heading.1": { fg: RGBA.fromHex(chatScreenTheme.accentCyan), bold: true },
  "markup.heading.2": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.heading.3": { fg: RGBA.fromHex(chatScreenTheme.accentPurple), bold: true },
  "punctuation.definition.heading": { fg: RGBA.fromHex(chatScreenTheme.textDim), bold: true },
  "markup.italic": { fg: RGBA.fromHex(chatScreenTheme.textPrimary), italic: true },
  "markup.bold": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.strong": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.strikethrough": { fg: RGBA.fromHex(chatScreenTheme.textDim), dim: true },
  "markup.link": { fg: RGBA.fromHex(chatScreenTheme.textSecondary) },
  "markup.link.bracket.close": { fg: RGBA.fromHex(chatScreenTheme.textSecondary) },
  "markup.link.label": { fg: RGBA.fromHex(chatScreenTheme.accentCyan), underline: true },
  "markup.link.url": { fg: RGBA.fromHex(chatScreenTheme.textSecondary), dim: true },
  "markup.list": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.list.bullet": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.list.enumeration": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.list.marker": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.list.numbered": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.list.ordered": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.list.unordered": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "punctuation.definition.list": { fg: RGBA.fromHex(chatScreenTheme.accentAmber), bold: true },
  "markup.list.checked": { fg: RGBA.fromHex(chatScreenTheme.accentGreen) },
  "markup.list.unchecked": { fg: RGBA.fromHex(chatScreenTheme.textDim) },
  "markup.quote": { fg: RGBA.fromHex(chatScreenTheme.textSecondary), italic: true },
  "markup.quote.marker": { fg: RGBA.fromHex(chatScreenTheme.accentPrimaryMuted), bold: true },
  "punctuation.definition.quote": { fg: RGBA.fromHex(chatScreenTheme.accentPrimaryMuted), bold: true },
  "markup.raw": { fg: RGBA.fromHex(chatScreenTheme.accentGreen), bold: true },
  "markup.raw.inline": { fg: RGBA.fromHex(chatScreenTheme.accentGreen), bold: true },
  "markup.raw.block": { fg: RGBA.fromHex(chatScreenTheme.textPrimary) },
  "markup.fenced_code.block": { fg: RGBA.fromHex(chatScreenTheme.textPrimary) },
  "markup.table": { fg: RGBA.fromHex(chatScreenTheme.textPrimary) },
  "markup.table.header": { fg: RGBA.fromHex(chatScreenTheme.accentCyan), bold: true },
  "punctuation.separator.table": { fg: RGBA.fromHex(chatScreenTheme.borderSubtle) },
  "diff.plus": { fg: RGBA.fromHex(chatScreenTheme.accentGreen) },
  "diff.minus": { fg: RGBA.fromHex(chatScreenTheme.accentRed) },
  "diff.delta": { fg: RGBA.fromHex(chatScreenTheme.accentCyan), bold: true },
  "punctuation.definition.inserted": { fg: RGBA.fromHex(chatScreenTheme.accentGreen) },
  "punctuation.definition.deleted": { fg: RGBA.fromHex(chatScreenTheme.accentRed) },
  character: { fg: RGBA.fromHex(chatScreenTheme.accentAmber) },
  "character.special": { fg: RGBA.fromHex(chatScreenTheme.accentPink) },
  label: { fg: RGBA.fromHex(chatScreenTheme.accentPrimaryMuted) },
  import: { fg: RGBA.fromHex(chatScreenTheme.accentPurple), bold: true },
  keyword: { fg: RGBA.fromHex(chatScreenTheme.accentPurple), bold: true },
  "keyword.import": { fg: RGBA.fromHex(chatScreenTheme.accentPurple), bold: true },
  string: { fg: RGBA.fromHex(chatScreenTheme.accentAmber) },
  "string.special.url": { fg: RGBA.fromHex(chatScreenTheme.accentCyan), underline: true },
  comment: { fg: RGBA.fromHex(chatScreenTheme.textDim), italic: true },
  number: { fg: RGBA.fromHex(chatScreenTheme.accentAmber) },
  boolean: { fg: RGBA.fromHex(chatScreenTheme.accentAmber) },
  constant: { fg: RGBA.fromHex(chatScreenTheme.accentAmber) },
  function: { fg: RGBA.fromHex(chatScreenTheme.accentCyan) },
  "function.call": { fg: RGBA.fromHex(chatScreenTheme.accentCyan) },
  type: { fg: RGBA.fromHex(chatScreenTheme.accentCyan) },
  property: { fg: RGBA.fromHex(chatScreenTheme.accentPrimaryMuted) },
  variable: { fg: RGBA.fromHex(chatScreenTheme.textPrimary) },
  parameter: { fg: RGBA.fromHex(chatScreenTheme.textPrimary) },
  operator: { fg: RGBA.fromHex(chatScreenTheme.textSecondary) },
  punctuation: { fg: RGBA.fromHex(chatScreenTheme.textSecondary) },
  "punctuation.special": { fg: RGBA.fromHex(chatScreenTheme.accentPink) },
  tag: { fg: RGBA.fromHex(chatScreenTheme.accentCyan) },
  attribute: { fg: RGBA.fromHex(chatScreenTheme.accentAmber) },
  decorator: { fg: RGBA.fromHex(chatScreenTheme.accentAmber) },
  namespace: { fg: RGBA.fromHex(chatScreenTheme.accentPrimaryMuted) },
  module: { fg: RGBA.fromHex(chatScreenTheme.accentPrimaryMuted) },
  escape: { fg: RGBA.fromHex(chatScreenTheme.accentPink) },
});

export const syntaxHighlightSpanForegroundColors: Record<SyntaxHighlightSpanStyle, string> = {
  keyword: githubLikeTerminalCodeColors.keyword,
  identifier: githubLikeTerminalCodeColors.foreground,
  string: githubLikeTerminalCodeColors.string,
  comment: githubLikeTerminalCodeColors.comment,
  module: githubLikeTerminalCodeColors.module,
  type: githubLikeTerminalCodeColors.type,
  number: githubLikeTerminalCodeColors.number,
  symbol: githubLikeTerminalCodeColors.punctuation,
  self: githubLikeTerminalCodeColors.constant,
  decorator: githubLikeTerminalCodeColors.decorator,
};

export const codeLineNumberGutterForegroundColor = RGBA.fromHex(githubLikeTerminalCodeColors.muted);

export const assistantMarkdownInlineCodeForegroundColor = RGBA.fromHex(chatScreenTheme.accentGreen);
export const assistantMarkdownStrongForegroundColor = RGBA.fromHex(chatScreenTheme.accentAmber);
export const assistantMarkdownDiffAdditionForegroundColor = RGBA.fromHex(chatScreenTheme.accentGreen);
export const assistantMarkdownDiffRemovalForegroundColor = RGBA.fromHex(chatScreenTheme.accentRed);
export const assistantMarkdownDiffMetadataForegroundColor = RGBA.fromHex(chatScreenTheme.accentCyan);
export const assistantMarkdownDiffChromeForegroundColor = RGBA.fromHex(chatScreenTheme.textDim);

export const terminalDiffColors = {
  addedBackground: githubLikeTerminalCodeColors.diffAdditionBackground,
  removedBackground: githubLikeTerminalCodeColors.diffRemovalBackground,
  contextBackground: githubLikeTerminalCodeColors.canvas,
  addedContentBackground: githubLikeTerminalCodeColors.diffAdditionContentBackground,
  removedContentBackground: githubLikeTerminalCodeColors.diffRemovalContentBackground,
  contextContentBackground: githubLikeTerminalCodeColors.canvas,
  addedSignForeground: githubLikeTerminalCodeColors.diffAddition,
  removedSignForeground: githubLikeTerminalCodeColors.diffRemoval,
  lineNumberForeground: githubLikeTerminalCodeColors.muted,
  lineNumberBackground: githubLikeTerminalCodeColors.canvas,
  addedLineNumberBackground: githubLikeTerminalCodeColors.diffAdditionBackground,
  removedLineNumberBackground: githubLikeTerminalCodeColors.diffRemovalBackground,
} as const;
